# Generated by Django 4.2.27 on 2026-04-20 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_rating', models.CharField(blank=True, choices=[('too_high', 'Too high'), ('accurate', 'Accurate'), ('too_low', 'Too low')], max_length=16, null=True)),
                ('usefulness', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('match_score', models.IntegerField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('jd_excerpt', models.TextField(blank=True, default='')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='matcher.analysishistory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='matcher_ana_created_c4b02b_idx'), models.Index(fields=['score_rating'], name='matcher_ana_score_r_d84ec8_idx')],
            },
        ),
    ]
