# Generated by Django 4.2.27 on 2026-04-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_analysisfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('mentions', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_promoted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-mentions', '-last_seen'],
                'indexes': [models.Index(fields=['-mentions'], name='matcher_eme_mention_65a2ec_idx'), models.Index(fields=['-last_seen'], name='matcher_eme_last_se_2ec8e6_idx'), models.Index(fields=['is_promoted'], name='matcher_eme_is_prom_6b234e_idx')],
            },
        ),
    ]
